# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('picture', models.CharField(max_length=250)),
                ('time_created', models.DateTimeField(editable=False)),
                ('time_updated', models.DateTimeField()),
            ],
        ),
    ]
