# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasp', '0005_auto_20171103_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
