# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasp', '0006_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
