# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasp', '0007_auto_20171103_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
